/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright (c) 2026 FoBE Studio */

/* Offline fixture capture only. Never link the implementation under test. */
#include <CayenneLPP.h>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <map>
#include <vector>

using Bytes = std::vector<uint8_t>;

struct Location {
	bool present;
	int32_t latitude;
	int32_t longitude;
};

static Bytes bytes(CayenneLPP &reference)
{
	Bytes result(reference.getSize());

	reference.copy(result.data());
	return result;
}

static void emit_bytes(const Bytes &payload)
{
	std::printf("{ ");
	if (payload.empty()) {
		std::printf("0");
	}
	for (size_t i = 0; i < payload.size(); ++i) {
		if (i != 0) {
			std::printf(i % 8 == 0 ? ",\n\t\t  " : ", ");
		}
		std::printf("0x%02x", payload[i]);
	}
	std::printf(" }");
}

static void emit_scalar(const char *name, const char *function, const char *literal,
			float value, uint8_t (CayenneLPP::*add)(uint8_t, float))
{
	CayenneLPP reference(64);

	assert((reference.*add)(3, value) != 0);
	assert(reference.getError() == LPP_ERROR_OK);
	std::printf("\t{ \"%s\", cayenne_lpp_add_%s, %sf, %uU,\n\t  ",
		    name, function, literal, reference.getSize());
	emit_bytes(bytes(reference));
	std::printf(" },\n");
}

static void emit_gps(const char *name, const char *lat, const char *lon, const char *alt,
		     float latitude, float longitude, float altitude)
{
	CayenneLPP reference(64);

	assert(reference.addGPS(7, latitude, longitude, altitude) == 11);
	assert(reference.getError() == LPP_ERROR_OK);
	std::printf("\t{ \"%s\", %sf, %sf, %sf,\n\t  ", name, lat, lon, alt);
	emit_bytes(bytes(reference));
	std::printf(" },\n");
}

static Location decode(Bytes payload)
{
	Location result = {};

	if (!payload.empty()) {
		CayenneLPP reference(64);
		std::map<uint8_t, CayenneLPPMessage> messages;

		reference.decode(payload.data(), payload.size(), messages);
		auto gps = messages.find(7);

		if (gps != messages.end()) {
			result.present = true;
			result.latitude = std::lround(gps->second.gps[0] * 10000.0f) * 100;
			result.longitude = std::lround(gps->second.gps[1] * 10000.0f) * 100;
		}
	}
	return result;
}

static void emit_location(const char *name, const Bytes &payload, Location expected)
{
	std::printf("\t{ \"%s\", %zuU,\n\t  ", name, payload.size());
	emit_bytes(payload);
	std::printf(",\n\t  %s, %d, %d },\n", expected.present ? "true" : "false",
		    expected.latitude, expected.longitude);
}

int main()
{
	std::printf("/* SPDX-" "License-Identifier: Apache-2.0 */\n"
		    "/* Copyright (c) 2026 FoBE Studio */\n"
		    "/* Generated by tools/capture_reference.cpp; see README.md. */\n\n"
		    "static const struct scalar_vector scalar_vectors[] = {\n");
	emit_scalar("analog zero", "analog_input", "0.0", 0.0f, &CayenneLPP::addAnalogInput);
	emit_scalar("analog negative", "analog_input", "-12.34", -12.34f,
		    &CayenneLPP::addAnalogInput);
	emit_scalar("barometric", "barometric_pressure", "1001.2", 1001.2f,
		    &CayenneLPP::addBarometricPressure);
	emit_scalar("distance", "distance", "12.345", 12.345f, &CayenneLPP::addDistance);
	emit_scalar("humidity", "relative_humidity", "55.5", 55.5f,
		    &CayenneLPP::addRelativeHumidity);
	emit_scalar("temperature negative", "temperature", "-4.2", -4.2f,
		    &CayenneLPP::addTemperature);
	emit_scalar("voltage", "voltage", "4.19", 4.19f, &CayenneLPP::addVoltage);
	emit_scalar("current", "current", "0.123", 0.123f, &CayenneLPP::addCurrent);
	emit_scalar("power", "power", "77.0", 77.0f, &CayenneLPP::addPower);
	emit_scalar("altitude negative", "altitude", "-15.0", -15.0f, &CayenneLPP::addAltitude);
	std::printf("};\n\nstatic const struct gps_vector gps_vectors[] = {\n");
	emit_gps("gps positive", "22.5432", "114.0579", "12.34", 22.5432f, 114.0579f, 12.34f);
	emit_gps("gps negative", "-22.5432", "-114.0579", "-1.23", -22.5432f, -114.0579f, -1.23f);
	std::printf("};\n\nstatic const uint8_t combined_bytes[] = ");
	CayenneLPP combined(15);

	assert(combined.addVoltage(3, 4.2f) == 4);
	assert(combined.addGPS(7, 22.1f, 114.2f, 0.0f) == 15);
	const Bytes before_overflow = bytes(combined);

	assert(combined.addPower(3, 11.0f) == 0);
	assert(combined.getError() == LPP_ERROR_OVERFLOW);
	assert(bytes(combined) == before_overflow);
	emit_bytes(before_overflow);
	std::printf(";\n\nstatic const struct location_vector location_vectors[] = {\n");
	emit_location("empty payload", {}, {});
	CayenneLPP builder(64);

	builder.addVoltage(3, 4.2f);
	builder.addTemperature(4, 22.5f);
	emit_location("non gps only", bytes(builder), decode(bytes(builder)));
	builder.reset();
	builder.addGPS(7, 22.5432f, 114.0579f, 0.0f);
	emit_location("single gps", bytes(builder), decode(bytes(builder)));
	builder.reset();
	builder.addVoltage(3, 4.2f);
	builder.addGPS(7, 22.5001f, 114.0002f, 0.0f);
	builder.addPower(4, 9.0f);
	emit_location("gps with other fields", bytes(builder), decode(bytes(builder)));
	builder.reset();
	builder.addGPS(7, 1.1111f, 2.2222f, 0.0f);
	builder.addTemperature(3, 20.0f);
	builder.addGPS(7, -3.3333f, -4.4444f, 0.0f);
	emit_location("last gps wins", bytes(builder), decode(bytes(builder)));
	builder.reset();
	builder.addGPS(7, 11.1111f, 22.2222f, 0.0f);
	Bytes prefix = bytes(builder);
	Bytes payload = prefix;

	emit_location("gps prefix before unknown", prefix, decode(prefix));
	payload.insert(payload.end(), {3, 0xee, 0xaa});
	emit_location("unknown after gps", payload, decode(payload));
	payload = {3, 0xee, 0x55};
	payload.insert(payload.end(), prefix.begin(), prefix.end());
	emit_location("unknown before gps", payload, decode(payload));
	payload = prefix;
	payload.insert(payload.end(), {3, 103, 0});
	emit_location("truncated after gps", payload, decode(payload));
	builder.reset();
	builder.addGPS(7, 12.3456f, 23.4567f, 0.0f);
	prefix = bytes(builder);
	payload = {
		3, 100, 0, 0, 0, 1, 3, 118, 0, 0, 0, 1, 3, 120, 1,
		3, 125, 0, 1, 3, 131, 0, 0, 0, 1, 3, 132, 0, 1,
		3, 133, 0, 0, 0, 1, 3, 135, 0x11, 0x22, 0x33, 3, 142, 1,
		3, 240, 8, 1, 2, 3, 4, 5, 6, 7,
	};
	payload.insert(payload.end(), prefix.begin(), prefix.end());
	/* Existing skip-field contract: expected GPS comes from the valid suffix. */
	emit_location("known skipped types before gps", payload, decode(prefix));
	payload = {3, 240, 8, 1, 2};
	payload.insert(payload.end(), prefix.begin(), prefix.end());
	/* Existing malformed-field contract; do not feed this to the reference decoder. */
	emit_location("malformed polyline before gps", payload, {});
	std::printf("};\n");
}
